name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Validate Xcode project
        run: |
          echo "Checking Xcode project structure..."
          ls -la twentyfour.xcodeproj/
          echo "Project file contents:"
          cat twentyfour.xcodeproj/project.pbxproj | head -n 20

      - name: Build
        run: |
          xcodebuild clean build analyze \
            -project twentyfour.xcodeproj \
            -scheme twentyfour \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
